// frontend/onlinesushishop-react/src/pages/EditItem.tsx
import {useParams} from "react-router";
import {useEffect, useState} from "react";
import Item from "../interfaces/Item.tsx";
import MainCategory from "../interfaces/MainCategory.tsx";
import Subcategory from "../interfaces/Subcategory.tsx";
import {getItemById, getMainCategories, getSubcategories, putItem} from "../services/Api.tsx";
import axios from "axios";
import {
    Box,
    Button,
    Checkbox,
    FormControlLabel,
    FormGroup,
    FormLabel,
    Radio,
    RadioGroup,
    TextField,
    Typography
} from "@mui/material";

export default function EditItem() {
    const param = useParams();
    // const [item, setItem] = useState<Item[]>([]);
    const [itemById, setItemById] = useState<Item>({
        itemActualPrice: 0,
        itemComment: "",
        itemId: 0,
        itemImageUrl: "",
        itemIsHidden: 0,
        itemMainCategory: "",
        itemName: "",
        itemOldPrice: 0,
        itemSubcategories: []
    })
    const [mainCategory, setMainCategory] = useState<MainCategory[]>([])
    const [subcategory, setSubcategory] = useState<Subcategory[]>([])
    const [loading, setLoading] = useState<boolean>(true);
    const [error, setError] = useState<string | null>(null);

    const [formState, setFormState] = useState({
        itemId: "",
        name: "",
        actualPrice: "",
        oldPrice: "",
        imageURL: "",
        description: "",
        mainCategory: "",
        isHidden: 1,
        subcategories: []
    })

    useEffect(() => {
        const fetchMainCategories = async () => {
            const responseFetchMainCategories = await getMainCategories();
            return responseFetchMainCategories;
        }

        const fetchSubcategories = async () => {
            const responseFetchSubcategories = await getSubcategories();
            return responseFetchSubcategories;
        }

        const fetchItemById = async () => {
            const responseFetchItemById = await getItemById((Number(param.itemId)));
            return responseFetchItemById;
        }

        axios.all([fetchMainCategories(), fetchSubcategories(), fetchItemById()])
            .then(axios.spread((dataMainCategories, dataSubcategories, dataItemById) => {
                console.log(`dataMainCategories:`);
                console.log(dataMainCategories);
                setMainCategory(dataMainCategories);
                console.log(`dataSubcategories:`);
                console.log(dataSubcategories);
                setSubcategory(dataSubcategories);
                console.log(`dataItemById:`);
                console.log(dataItemById);
                setItemById(dataItemById);
                setLoading(false);

                setFormState({
                    itemId: dataItemById.itemId,
                    name: dataItemById.itemName,
                    actualPrice: dataItemById.itemActualPrice,
                    oldPrice: dataItemById.itemOldPrice,
                    description: dataItemById.itemComment,
                    imageURL: dataItemById.itemImageUrl,
                    mainCategory: dataItemById.itemMainCategory,
                    isHidden: dataItemById.itemIsHidden,
                    subcategories: dataSubcategories.map((subcat: Subcategory) => ({
                        subcategoryId: subcat.subcategoryId,
                        subcategoryName: subcat.subcategoryName,
                        isChecked: dataItemById.itemSubcategories.some((itemSubcat: Subcategory) =>
                            itemSubcat.subcategoryName === subcat.subcategoryName
                        ),
                    })),
                })
            }))
            .catch((error) => {
                console.error(`Error during fetch ${error}`);
                setError((error as Error).message);
            });
    }, [param.itemId]);

    const handleSubmit = async (e) => {
        e.preventDefault();
        const askConfirmUpdate: boolean = confirm("Update item?")

        if (askConfirmUpdate) {
            const formStateToPut = {...formState};

            formStateToPut.subcategories = formStateToPut.subcategories
                .filter((sub) => sub.isChecked)
                .map((sub) => sub.subcategoryId)
            ;

            formStateToPut.mainCategory = mainCategory
                .filter((maincat) => maincat.mainCategoryName === formStateToPut.mainCategory)
                .map((maincat) => maincat.mainCategoryId)[0]
            ;

            try {
                const responsePostFormSate = await putItem(formStateToPut);
                console.info(responsePostFormSate);
                alert("Item successfully updated!");
            } catch (error) {
                console.error("Error:", (error as any).response?.data || (error as Error).message);
            }

            console.info(`Form submitted: `)
            console.table(formStateToPut)
        }
    }

    const handleInputChange = (e, index = null) => {
        const {name, value, checked, type} = e.target;

        setFormState((prevState) => {
            const updatedState = {...prevState};

            if (type === "checkbox") {
                if (name === "isHidden") {
                    updatedState.isHidden = checked ? 1 : 0;
                } else if (index !== null) {
                    const updatedSubcategories = [...prevState.subcategories]
                    updatedSubcategories[index] = {
                        ...updatedSubcategories[index],
                        isChecked: checked
                    };
                    updatedState.subcategories = updatedSubcategories;
                }
            } else {
                updatedState[name] = value;
            }

            return updatedState;
        })


    }

    const renderEditItemPage = () => {
        if (loading) return <p>Loading components...</p>;
        if (error) return <p>Error {error}</p>;
        if (itemById.itemId === undefined) return <p>There is no item by id {param.itemId}</p>;

        return (
            <>
                <Typography variant="h4">Edit item</Typography>
                <form onSubmit={handleSubmit} style={{backgroundColor: "white"}}>
                    <TextField
                        label="Name"
                        name="name"
                        value={formState.name}
                        onChange={handleInputChange}
                        fullWidth
                        margin="normal"
                        required
                    />
                    <TextField
                        label="Actual price in PLN"
                        name="actualPrice"
                        value={formState.actualPrice}
                        onChange={handleInputChange}
                        fullWidth
                        margin="normal"
                        required
                        type="number"
                        slotProps={{
                            htmlInput: {
                                min: 1
                            }
                        }}
                    />
                    <TextField
                        label="Old price in PLN"
                        name="oldPrice"
                        value={formState.oldPrice}
                        onChange={handleInputChange}
                        fullWidth
                        margin="normal"
                        required
                        type="number"
                        slotProps={{
                            htmlInput: {
                                min: 1
                            }
                        }}
                    />
                    <TextField
                        label="Image URL"
                        name="imageURL"
                        value={formState.imageURL}
                        onChange={handleInputChange}
                        fullWidth
                        margin="normal"
                        required
                        multiline
                        variant="outlined"
                        rows={4}
                    />
                    <TextField
                        label="Description"
                        name="description"
                        value={formState.description}
                        onChange={handleInputChange}
                        fullWidth
                        margin="normal"
                        required
                        multiline
                        variant="outlined"
                        rows={4}
                    />
                    <FormLabel component="legend" sx={{marginTop: 2, textAlign: "left"}}>
                        Choose a main category:
                    </FormLabel>
                    <RadioGroup
                        name="mainCategory"
                        onChange={handleInputChange}
                        value={formState.mainCategory}
                    >
                        {mainCategory && mainCategory.length > 0 ? (
                            mainCategory.map((mc, index) => (
                                <FormControlLabel
                                    key={index}
                                    value={mc.mainCategoryName}
                                    control={<Radio/>}
                                    label={mc.mainCategoryName}
                                    sx={{
                                        color: "black"
                                    }}
                                />
                            ))
                        ) : (
                            <Typography variant="body2" color="error">No categories available!</Typography>
                        )}
                    </RadioGroup>

                    <FormLabel component="legend" sx={{marginTop: 2, textAlign: "left"}}>
                        Is hidden?
                    </FormLabel>
                    <FormControlLabel
                        control={
                            <Checkbox
                                name="isHidden"
                                checked={formState.isHidden === 1}
                                onChange={handleInputChange}
                            />
                        }
                        label="Is hidden"
                        sx={{
                            color: "black",
                            textAlign: "left",
                            display: "flex",
                            justifyContent: "flex-start",
                        }}

                    />

                    <FormLabel component="legend" sx={{marginTop: 2, textAlign: "left"}}>
                        Choose a subcategories:
                    </FormLabel>
                    <FormGroup>
                        {formState.subcategories.map((subcat, index) => (
                            <FormControlLabel
                                key={subcat.subcategoryId}
                                control={
                                    <Checkbox
                                        checked={subcat.isChecked}
                                        onChange={(e) => handleInputChange(e, index)}
                                    />
                                }
                                label={subcat.subcategoryName}
                                sx={{
                                    color: "black"
                                }}
                            />
                        ))}
                    </FormGroup>


                    <Button type="submit" variant="contained" color="primary">
                        Update
                    </Button>
                </form>
                <Box
                    sx={{backgroundColor: "blue", color: 'white', borderRadius: '4px', mt: 4, p: 2}}>
                    <pre>{JSON.stringify(formState, null, 2)}</pre>
                </Box>
            </>
        );

    };

    return (
        <>
            {renderEditItemPage()}
        </>
    );
};

// frontend/onlinesushishop-angular/src/app/features/edit-item/edit-item.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {ItemService} from '../services/item.service';
import {ActivatedRoute, ParamMap} from '@angular/router';
import {NavbarService} from '../../layout/services/navbar.service';
import {FormArray, FormBuilder, ReactiveFormsModule} from '@angular/forms';
import {forkJoin, Subscription} from 'rxjs';
import {GlobalService} from '../../services/global.service';
import {JsonPipe} from '@angular/common';

@Component({
  selector: 'app-edit-item',
  imports: [
    ReactiveFormsModule,
    JsonPipe
  ],
  templateUrl: './edit-item.component.html',
  styleUrl: './edit-item.component.css'
})
export class EditItemComponent implements OnInit, OnDestroy {
  public itemId: any
  public itemById: any = {};
  public mainCategories: any = [];
  public subcategories: any = [];

  private getItemByIdSubscription?: Subscription;
  private getItemSubscription?: Subscription;
  private getMainCategoriesSubscription?: Subscription;
  private getSubcategoriesSubscription?: Subscription;
  private putItemSubscription?: Subscription;

  editItemForm: any;

  constructor(private itemService: ItemService,
              private activatedRoute: ActivatedRoute,
              private navbarService: NavbarService,
              private fb: FormBuilder,
              private globalService: GlobalService) {

  }

  ngOnDestroy(): void {
    this.getItemByIdSubscription?.unsubscribe();
    this.getItemSubscription?.unsubscribe();
    this.getMainCategoriesSubscription?.unsubscribe();
    this.getSubcategoriesSubscription?.unsubscribe();
    this.putItemSubscription?.unsubscribe();
  }

  ngOnInit(): void {
    this.editItemForm = this.fb.group({
      id: [''],
      name: [''],
      actualPrice: [''],
      oldPrice: [''],
      description: [''],
      mainCategory: [''],
      imageURL: [''],
      isHidden: [''],
      subcategories: this.fb.array([])
    })

    this.activatedRoute.paramMap.subscribe((params: ParamMap): void => {
      this.itemId = params.get('id');
    });

    forkJoin([
      this.navbarService.getMainCategories(),
      this.itemService.getSubcategories()
    ]).subscribe(([mainCategories, subcategories]: [any, any]): void => {
      this.mainCategories = mainCategories;
      this.subcategories = subcategories;
      this.getItemById(this.itemId);
    })
  }

  patchSubcategories(id: number, check: boolean, name: string) {
    return this.fb.group({
      subcategoryId: [id],
      isChecked: [check],
      subcategoryName: [name]
    })
  }

  get getSubcategoriesFormArray() {
    return this.editItemForm.get('subcategories') as FormArray
  }

  private getItemById(itemId: any): void {
    this.globalService.logGetMessage("Item id", this.itemId);
    const controls = this.editItemForm.get('subcategories') as FormArray;
    this.getItemByIdSubscription = this.itemService.getItemById(itemId)
      .subscribe({
        next: (data: any): void => {
          this.itemById = data;
          this.globalService.logGetMessage(`Item by id ${itemId} from getItemById`, data);

          this.editItemForm.get('id')?.setValue(this.itemById.itemId);
          this.editItemForm.get('name')?.setValue(this.itemById.itemName);
          this.editItemForm.get('actualPrice')?.setValue(this.itemById.itemActualPrice);
          this.editItemForm.get('oldPrice')?.setValue(this.itemById.itemOldPrice);
          this.editItemForm.get('description')?.setValue(this.itemById.itemComment);
          this.editItemForm.get('imageURL')?.setValue(this.itemById.itemImageUrl);
          this.editItemForm.get('isHidden')?.setValue(this.itemById.itemIsHidden);
          this.editItemForm.get('mainCategory')?.setValue(this.itemById.itemMainCategory);

          controls.clear();

          this.subcategories.forEach((sub: any) => {
            if (this.itemById.itemSubcategories.find((value: any) => value.subcategoryName === sub.subcategoryName))
              controls.push(this.patchSubcategories(sub.subcategoryId, true, sub.subcategoryName))
            else
              controls.push(this.patchSubcategories(sub.subcategoryId, false, sub.subcategoryName))
          })


        },
        error: err => {
          console.error(err);
        }
      })
  }

  submitEditItem() {
    let askConfirmUpdate: boolean = confirm("Update item?")

    if (askConfirmUpdate) {
      const editItemFormValue: any = this.editItemForm.value;
      const editItemFormValueArray = Array.isArray(editItemFormValue) ? editItemFormValue : [editItemFormValue];

      editItemFormValueArray.forEach((item: any) => {
        // item.subcategories = item.subcategories
        //   .filter((sub: any) => sub.isChecked !== false)
        //   .map((sub: any) => {
        //     delete sub.isChecked;
        //     sub.subcategoryIsHidden = 0;
        //     return sub;
        //   });

        item.subcategories = item.subcategories
          .filter((sub: any) => sub.isChecked)
          .map((sub: any) => sub.subcategoryId)

        item.isHidden = Number(item.isHidden);

        item.mainCategory = this.mainCategories
          .filter((category: any) => category.mainCategoryName === item.mainCategory)
          .map((category: any) => category.mainCategoryId)[0]
      });

      // console.log("Update click!");
      // // console.log(editItemFormValue)
      // console.log(editItemFormValueArray[0])
      //
      // const subcategories = this.editItemForm.get('subcategories')?.value;
      // console.log("subcategories:", subcategories, "typ:", typeof subcategories);
      //
      // console.log("Wysyłane dane:", JSON.stringify(editItemFormValueArray));

      this.putItemSubscription = this.itemService.putItem(editItemFormValueArray[0])
        .subscribe({
          next: (): void => {
            alert(`Updated! The page will reload!`)
            window.location.reload();
          },
          error: err => {
            console.error(err)
          }
        })
    }
  }
}

<!--<p>edit-item works!</p>-->
<div class="flex-container">
  <div>
    <form [formGroup]="editItemForm" (submit)="submitEditItem()">
      <fieldset>
        <legend>Edit {{ itemById?.itemName }}</legend>

        <table>
          <tr>
            <td><label for="item-name">Name</label></td>
            <td><input type="text" formControlName="name" id="item-name"></td>
          </tr>

          <tr>
            <td><label for="actual-price">Actual price in PLN</label></td>
            <td><input type="number" formControlName="actualPrice" id="actual-price" min="0"></td>
          </tr>

          <tr>
            <td><label for="old-price">Old price in PLN</label></td>
            <td><input type="number" formControlName="oldPrice" id="old-price" min="0"></td>
          </tr>

          <tr>
            <td><label for="imageURL">Image URL</label></td>
            <td><textarea formControlName="imageURL" id="imageURL" rows="5" cols="30"></textarea></td>
          </tr>

          <tr>
            <td><label for="description">Description</label></td>
            <td><textarea id="description" formControlName="description" rows="10" cols="30"></textarea></td>
          </tr>

          <tr>
            <td colspan="2">Category:</td>
          </tr>

          @for (mc of mainCategories; track $index) {
            <tr>
              <td colspan="2">
                <label for="{{$index}}"><input id="{{$index}}"
                                               type="radio"
                                               formControlName="mainCategory"
                                               value="{{mc.mainCategoryName}}">
                  {{ mc.mainCategoryName }}</label>

              </td>
            </tr>
          } @empty {
            <tr>
              <td colspan="2">No categories!</td>
            </tr>
          }

          <tr>
            <td colspan="2">
              <div formArrayName="subcategories">
                @for (sub of getSubcategoriesFormArray.controls; track $index) {
                  <div formGroupName="{{$index}}">
                    <label for="subcategory-is-checked"></label>
                    <input type="checkbox" formControlName="isChecked" id="subcategory-is-checked">
                    |
                    <input formControlName="subcategoryName" readonly>
                  </div>
                }
              </div>
            </td>
          </tr>

          <tr>
            <td><label for="is-hidden">Hide?</label></td>
            <td><input type="checkbox" formControlName="isHidden" id="is-hidden"></td>
          </tr>

          <tr>
            <td colspan="2">
              <button type="submit">Update!</button>
            </td>
          </tr>
        </table>
      </fieldset>
    </form>
  </div>
</div>

<pre>
  <span style="color: white;background-color: blue;">{{ editItemForm.value | json }}</span>
</pre>
